/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/customers/{customerId}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get customer profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Customer identifier */
                    customerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Customer profile details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CustomerProfile"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{customerId}/spending/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get spending summary for a period */
        get: {
            parameters: {
                query?: {
                    period?: "7d" | "30d" | "90d" | "1y";
                };
                header?: never;
                path: {
                    customerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Spending summary for the selected period */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpendingSummary"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{customerId}/spending/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get spending by category with optional filters */
        get: {
            parameters: {
                query?: {
                    period?: "7d" | "30d" | "90d" | "1y";
                    startDate?: string;
                    endDate?: string;
                };
                header?: never;
                path: {
                    customerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Category spending breakdown */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CategoryBreakdownResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{customerId}/spending/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get monthly spending trends */
        get: {
            parameters: {
                query?: {
                    months?: number;
                };
                header?: never;
                path: {
                    customerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Monthly spending trends */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SpendingTrendsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{customerId}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get customer transactions with filtering and pagination */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                    category?: string;
                    startDate?: string;
                    endDate?: string;
                    sortBy?: "date_desc" | "date_asc" | "amount_desc" | "amount_asc";
                };
                header?: never;
                path: {
                    customerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Transactions list with pagination metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TransactionsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{customerId}/goals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get customer spending goals */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    customerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Spending goals for the customer */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["GoalsResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/customers/{customerId}/filters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get categories and date range presets used in dashboard filters */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    customerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Available filter metadata */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FilterMetadataResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CustomerProfile: {
            /** @example 12345 */
            customerId: string;
            /** @example John Doe */
            name: string;
            /**
             * Format: email
             * @example john.doe@email.com
             */
            email: string;
            /**
             * Format: date
             * @example 2023-01-15
             */
            joinDate: string;
            /** @example premium */
            accountType: string;
            /**
             * Format: double
             * @example 15420.5
             */
            totalSpent: number;
            /** @example ZAR */
            currency: string;
        };
        ComparedToPrevious: {
            /** @example 12.5 */
            spentChange?: number;
            /** @example -3.2 */
            transactionChange?: number;
        };
        SpendingSummary: {
            /**
             * @example 30d
             * @enum {string}
             */
            period: "7d" | "30d" | "90d" | "1y";
            /** @example 4250.75 */
            totalSpent: number;
            /** @example 47 */
            transactionCount: number;
            /** @example 90.44 */
            averageTransaction: number;
            /** @example Groceries */
            topCategory: string;
            comparedToPrevious?: components["schemas"]["ComparedToPrevious"];
        };
        CategorySummary: {
            /** @example Groceries */
            name: string;
            /** @example 1250.3 */
            amount: number;
            /** @example 29.4 */
            percentage: number;
            /** @example 15 */
            transactionCount: number;
            /** @example #FF6B6B */
            color: string;
            /** @example shopping-cart */
            icon: string;
        };
        DateRange: {
            /**
             * Format: date
             * @example 2024-08-16
             */
            startDate: string;
            /**
             * Format: date
             * @example 2024-09-16
             */
            endDate: string;
        };
        CategoryBreakdownResponse: {
            dateRange: components["schemas"]["DateRange"];
            /** @example 4250.75 */
            totalAmount: number;
            categories: components["schemas"]["CategorySummary"][];
        };
        MonthlyTrend: {
            /** @example 2024-01 */
            month: string;
            /** @example 3890.25 */
            totalSpent: number;
            /** @example 42 */
            transactionCount: number;
            /** @example 92.62 */
            averageTransaction: number;
        };
        SpendingTrendsResponse: {
            trends: components["schemas"]["MonthlyTrend"][];
        };
        Transaction: {
            /** @example txn_123456 */
            id: string;
            /**
             * Format: date-time
             * @example 2024-09-16T14:30:00Z
             */
            date: string;
            /** @example Pick n Pay */
            merchant: string;
            /** @example Groceries */
            category: string;
            /** @example 245.8 */
            amount: number;
            /** @example Weekly groceries */
            description: string;
            /** @example Credit Card */
            paymentMethod: string;
            /** @example shopping-cart */
            icon: string;
            /** @example #FF6B6B */
            categoryColor: string;
        };
        Pagination: {
            /** @example 1250 */
            total: number;
            /** @example 20 */
            limit: number;
            /** @example 0 */
            offset: number;
            /** @example true */
            hasMore: boolean;
        };
        TransactionsResponse: {
            transactions: components["schemas"]["Transaction"][];
            pagination: components["schemas"]["Pagination"];
        };
        Goal: {
            /** @example goal_001 */
            id: string;
            /** @example Entertainment */
            category: string;
            /** @example 1000 */
            monthlyBudget: number;
            /** @example 650.3 */
            currentSpent: number;
            /** @example 65.03 */
            percentageUsed: number;
            /** @example 12 */
            daysRemaining: number;
            /**
             * @example on_track
             * @enum {string}
             */
            status: "on_track" | "warning" | "exceeded";
        };
        GoalsResponse: {
            goals: components["schemas"]["Goal"][];
        };
        CategoryOption: {
            /** @example Groceries */
            name: string;
            /** @example #FF6B6B */
            color: string;
            /** @example shopping-cart */
            icon: string;
        };
        DateRangePreset: {
            /** @example Last 30 days */
            label: string;
            /** @example 30d */
            value: string;
        };
        FilterMetadataResponse: {
            categories: components["schemas"]["CategoryOption"][];
            dateRangePresets: components["schemas"]["DateRangePreset"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
